spring.application.name=ExpenseTracker
spring.config.import=optional:file:.env[.properties]
debug=true

spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update